# Generated by Django 4.1.7 on 2023-04-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
