# Generated by Django 4.1.7 on 2023-04-25 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'piece')], default='piece', max_length=50),
        ),
    ]
